model:
  target: models.unet.UNetModelSwin
  ckpt_path: ~
  params:
    image_size: 81
    in_channels: 1
    model_channels: 160
    out_channels: 1
    attention_resolutions: [80]  # 修改为与图像尺寸81更匹配
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 16
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 64
    window_size: 7  # 修改窗口大小使其与输入图像尺寸更适合
    mlp_ratio: 4
    cond_lq: True
    lq_size: 81

diffusion: 
  target: models.script_util.create_gaussian_diffusion
  params:
    sf: 4
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 15
    min_noise_level: 0.04
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True

data:
  train:
    type: realesrgan
    params:
      dir_paths: ['/home/wangpengkai/node/ResShift-master/ResShift-master/data/test']
      # txt_file_path: [
      #                 '/mnt/lustre/zsyue/database/ImageNet/train/image_path_all.txt', 
      #                 '/mnt/lustre/zsyue/database/FFHQ/files_txt/ffhq256.txt',
      #                ] 
      im_exts: ['JPEG', 'png', 'jpg', 'jpeg', 'JPEG', 'bmp']
      # io_backend:
      #   type: disk
      # blur_kernel_size: 21
      # kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      # kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      # sinc_prob: 0.1
      # blur_sigma: [0.2, 3.0]
      # betag_range: [0.5, 4.0]
      # betap_range: [1, 2.0]

      # blur_kernel_size2: 15
      # kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      # kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      # sinc_prob2: 0.1
      # blur_sigma2: [0.2, 1.5]
      # betag_range2: [0.5, 4.0]
      # betap_range2: [1, 2.0]

      # final_sinc_prob: 0.8

      # gt_size: 81
      # crop_pad_size: 300
      # use_hflip: True
      # use_rot: False
      # rescale_gt: True
  val:
    type: folder
    params:
      dir_path: /home/wangpengkai/node/ResShift-master/ResShift-master/testdata/RealSet128
      dir_path_extra: ~
      transform_type: default
      transform_kwargs:
          mean: 0.5
          std: 0.5
      im_exts: png
      length: ~
      recursive: False

train:
  lr: 5e-5
  batch: [16, 8]   # batchsize for training and validation
  use_fp16: False
  microbatch: 16
  seed: 123456
  global_seeding: False
  prefetch_factor: 4
  num_workers: 8
  ema_rate: 0.999
  iterations: 5000
  milestones: [5000, 500000]
  weight_decay: 0
  save_freq: 10000
  val_freq: 10000
  log_freq: [1000, 5000, 1] #[training loss, training images, val images]
  save_images: True  # save the images of tensorboard logging
  use_ema_val: True
  gpu: 0 
